sudo: false

language: go
go:
  - 1.4
  - 1.5

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get -t -v ./...

script:
  - OUT=`gofmt -l .`; if [ "$OUT" ]; then echo $OUT; exit 1; fi
  - OUT=`golint ./...`; if [ "$OUT" ]; then echo $OUT; exit 1; fi
  - go vet ./...
  - go test -v -coverprofile=cover.out -covermode=count
  - go tool cover -func=cover.out
  - goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN